#!/usr/bin/env python3
"""Testbench comparing the tile-model fabric against the gold netlist.

  gen_fabric_miter.py <gold_exposed.v> <ffmap.txt> <fabric.v> <out_tb.v>

Same stimulus into both, every mapped register compared each cycle, first
divergence reported.  The fabric's clock and reset ports are found by name --
the BUFG output and the IBUF net -- since the tile model does not reconstruct
either the clock tree or the IO buffers.
"""
import re, sys

gold_v, ffmap_p, fabric_v, out_p = sys.argv[1:5]
cycles = int(sys.argv[5]) if len(sys.argv) > 5 else 200

gold_ports = set(re.findall(r'^  output (?:\[\d+:\d+\] )?\\(\S+) ?;', open(gold_v).read(), re.M))
pairs = []
for line in open(ffmap_p):
    lab, net = line.rstrip('\n').split('\t')
    if lab in gold_ports:
        pairs.append((lab, net))

fab = open(fabric_v).read()
ins = re.findall(r'^  input wire (\w+)', fab, re.M)
clk = [i for i in ins if 'BUFGCTRL' in i]
rst = [i for i in ins if i not in clk]
if not clk:
    sys.exit('no BUFG output port in the fabric -- was the clock tree simplified?')

def w(n):
    return 'c_' + re.sub(r'[^A-Za-z0-9]', '_', n)

L = ['// AUTO-GENERATED by gen_fabric_miter.py', '`timescale 1ps/1ps', 'module tb;',
     '  reg clk = 0, rst = 1;', '  integer cyc = 0, bad;', '  always #5 clk = ~clk;',
     '  wire [7:0] led_g;']
for lab, _ in pairs:
    L.append('  wire %s;' % w(lab))
L.append('')
L.append('  gold u_gold (.sysclk_p(clk), .sysclk_n(~clk), .rst(rst), .led(led_g),')
L.append(',\n'.join('              .\\%s (%s)' % (lab, w(lab)) for lab, _ in pairs) + ');')
L.append('  fabric u_fab (' + ', '.join(['.%s(clk)' % c for c in clk] +
                                        ['.%s(rst)' % r for r in rst]) + ');')
L += ['', '  always @(posedge clk) begin', '    cyc <= cyc + 1;',
      '    if (cyc == 4) rst <= 0;', '    if (cyc > 5) begin', '      bad = 0;']
for lab, net in pairs:
    L.append('      if (%s !== u_fab.%s) begin bad=bad+1; $display("  cycle %%0d  %s  gold=%%b fabric=%%b", cyc, %s, u_fab.%s); end'
             % (w(lab), net, lab, w(lab), net))
L += ['      if (bad != 0) begin',
      '        $display("FIRST DIVERGENCE at cycle %0d (%0d of ' + str(len(pairs)) + ' registers)", cyc, bad);',
      '        $finish;', '      end', '    end',
      '    if (cyc > %d) begin $display("no divergence in %%0d cycles (%d registers)", cyc); $finish; end' % (cycles, len(pairs)),
      '  end', 'endmodule']
open(out_p, 'w').write('\n'.join(L) + '\n')
print('gen_fabric_miter: %d registers compared -> %s' % (len(pairs), out_p))
