#!/usr/bin/env python3
"""Generate a Verilator miter testbench from two FF-exposed netlists.

Both netlists must have been through yosys `expose -dff` (see expose_ffs.ys.in),
which turns every flip-flop output into a module port.  The testbench drives
identical stimulus into both, compares every matched flip-flop and every output
bit on each cycle, and reports the FIRST cycle at which anything diverges --
which is what turns "these differ" into "this register, this cycle, these
values".

  gen_miter_tb.py <gold_exposed.v> <out_tb.v> [cycles]

Correspondence is by port name: gold's exposed port `\\core.prbs[0]` pairs with
gate's `\\core.prbs[0]_i.Q`, the cell-name form yosys gives the wire after
flattening.  Register renaming has to have happened already -- see
annotate_lvs.py.
"""
import re, sys

gold_v, out_p = sys.argv[1], sys.argv[2]
cycles = int(sys.argv[3]) if len(sys.argv) > 3 else 3000

src = open(gold_v).read()
ffs = [n for n in re.findall(r'^  output (?:\[\d+:\d+\] )?(\\\S+) ?;', src, re.M)]
if not ffs:
    sys.exit('no exposed flip-flop ports in %s -- was expose -dff run?' % gold_v)

def w(n):
    return 'g_' + re.sub(r'[^A-Za-z0-9]', '_', n)

L = ['// AUTO-GENERATED by gen_miter_tb.py -- %d flip-flops + the output bits.' % len(ffs),
     '// Reports the first cycle at which the two netlists disagree.',
     '`timescale 1ps/1ps',
     'module tb;',
     '  reg clk = 0, rst = 1;',
     '  integer cyc = 0, bad;',
     '  wire [7:0] led_g, led_t;']
for n in ffs:
    L.append('  wire %s, %s;' % (w(n) + '_gold', w(n) + '_gate'))
L += ['',
      '  gold u_gold (.sysclk_p(clk), .sysclk_n(~clk), .rst(rst), .led(led_g),',
      ',\n'.join('              .%s (%s)' % (n, w(n) + '_gold') for n in ffs) + ');',
      '  gate u_gate (.sysclk_p(clk), .sysclk_n(~clk), .rst(rst), .led(led_t),',
      ',\n'.join('              .%s_i.Q (%s)' % (n, w(n) + '_gate') for n in ffs) + ');',
      '',
      '  always #5 clk = ~clk;',
      '',
      '  always @(posedge clk) begin',
      '    cyc <= cyc + 1;',
      '    if (cyc == 4) rst <= 0;',
      '    if (cyc > 4) begin',
      '      bad = 0;']
for n in ffs:
    L.append('      if (%s !== %s) begin bad=bad+1; $display("  cycle %%0d  %s  gold=%%b gate=%%b", cyc, %s, %s); end'
             % (w(n) + '_gold', w(n) + '_gate', n.lstrip('\\'), w(n) + '_gold', w(n) + '_gate'))
L += ['      if (led_g !== led_t) begin bad=bad+1; $display("  cycle %0d  led  gold=%b gate=%b", cyc, led_g, led_t); end',
      '      if (bad != 0) begin',
      '        $display("FIRST DIVERGENCE at cycle %0d (%0d signals)", cyc, bad);',
      '        $finish;',
      '      end',
      '    end',
      '    if (cyc > %d) begin $display("no divergence in %%0d cycles", cyc); $finish; end' % cycles,
      '  end',
      'endmodule']
open(out_p, 'w').write('\n'.join(L) + '\n')
print('gen_miter_tb: %d flip-flop comparisons -> %s' % (len(ffs), out_p))
